version: "3.7"
services:
  matomo:
    image: matomo:latest
    container_name: matomo
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      - MATOMO_DATABASE_HOST=db
      - MATOMO_DATABASE_ADAPTER=mysql
      - MATOMO_DATABASE_TABLES_PREFIX=matomo_
      - MATOMO_DATABASE_DBNAME=matomo
      - MATOMO_DATABASE_USERNAME=matomo
      - MATOMO_DATABASE_PASSWORD=matomo_pass
    volumes:
      - matomo-data:/var/www/html
  db:
    image: mariadb:10.6
    container_name: matomo-db
    command: --max-allowed-packet=64MB --innodb-log-file-size=64MB
    environment:
      - MYSQL_ROOT_PASSWORD=root_pass
      - MYSQL_DATABASE=matomo
      - MYSQL_USER=matomo
      - MYSQL_PASSWORD=matomo_pass
    volumes:
      - db-data:/var/lib/mysql
volumes:
  matomo-data:
  db-data:
